Comments = {
  March25th: 
    " On 25th of March, the actual total cases was much higher than predicted. This is more inline with the Italy trend, which could be a result of testing capacity increase. The actual fatality cases was much lower than predicted, which is an indication of patient care is mananged well. So, in the editor's oppinion, this is very good news! Things are improving :)",
  March26th:
  "         Editor's Analysis (7pm, 26 March)\:
  The prediction on the 26th of March was very close to actual, which indicates a stable trend. Introduction of a 'Lock down' in the UK on 23th March was at similar stage as in Italy. In a few days time, we should be able to tell if the UK lock down is more effective than that has been in Italy. The number of fatalities is taking a slight upward trend today. This could just be a fluctuation due to the low number yesterday. Generally, the UK is looking like to be doing better than Italy, but, non the less, still a very scary outlook.",

  March28th: "         Editor's Analysis (11:50pm, 27 March)\:
  Another bad day for the nubmer of fatilities, which put the trend in the UK increasingly closer to Italy. That is a pretty dreadful outlook.Data from China is added for comparison. China went to lock down on the 23rd of Jan when there is only arround 800 cases, the total cases start to show a slowing down trend from arround 20 days after the lock down. The official UK lock down is on the 23rd of March, when there is already over 6000 cases. Although, UK has announced social distancing and closing of pubs a few days before that. The shielding of 1.2 million vounerable people is also a unique approach in comparison with other countries. If UK follows a similar pattern like have seen in China, we will start to see a slow down of new cases arround mid April. Fatality rate will start to slow down about 10 days after that. The UK lock down happened at a much later stage than that of China, but, slightly earlier than Italy. An earlier lockdown in China and Korean has been proved to achieve lower fatality rate. The effect of the UK approach is yet to be seen."

}